// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLib.Web.Data;

#nullable disable

namespace SmartLib.Web.Migrations
{
    [DbContext(typeof(SmartLibDbContext))]
    partial class SmartLibDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartLib.Web.Models.ChiTietMuonTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaCuonSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaCuonSach");

                    b.HasIndex("MaPhieu");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietMuonTra");
                });

            modelBuilder.Entity("SmartLib.Web.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("SmartLib.Web.Models.CuonSach", b =>
                {
                    b.Property<string>("MaCuonSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCuonSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CuonSach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.DanhGiaSach", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaSach");

                    b.ToTable("DanhGiaSach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.DocGia", b =>
                {
                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Khoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTheTV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTaoThe")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThaiThe")
                        .HasColumnType("bit");

                    b.HasKey("MaDocGia");

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.KeSach", b =>
                {
                    b.Property<string>("MaKe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNXBPhuTrach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTheLoaiPhuTrach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<int?>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TenKe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("ViTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKe");

                    b.HasIndex("MaNXBPhuTrach");

                    b.HasIndex("MaTheLoaiPhuTrach");

                    b.ToTable("KeSach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.MuonTra", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("DaGiaHan")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayHenTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaNV");

                    b.ToTable("MuonTra");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhaXuatBan", b =>
                {
                    b.Property<string>("MaNXB")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNXB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNXB");

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaChucVu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNV");

                    b.HasIndex("MaChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaNV");

                    b.ToTable("NhatKyHoatDong");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Reservation", b =>
                {
                    b.Property<int>("MaReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaReservation"));

                    b.Property<bool>("DaMuon")
                        .HasColumnType("bit");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPhieuMuon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaReservation");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaSach");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AnhBia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNXB")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTheLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuongKhaDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSach");

                    b.HasIndex("MaKe");

                    b.HasIndex("MaNXB");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Sach_TacGia", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaTacGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaSach", "MaTacGia");

                    b.HasIndex("MaTacGia");

                    b.ToTable("Sach_TacGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TacGia", b =>
                {
                    b.Property<string>("MaTacGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TheLoai", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TheThuVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaDocGia");

                    b.ToTable("TheThuVien");
                });

            modelBuilder.Entity("SmartLib.Web.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaSach");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaSach");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("SmartLib.Web.Models.WishlistFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDocGia")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaDocGia");

                    b.ToTable("WishlistFolder");
                });

            modelBuilder.Entity("SmartLib.Web.Models.WishlistPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiSoThich")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDocGia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaRef")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaDocGia");

                    b.ToTable("WishlistPreference");
                });

            modelBuilder.Entity("SmartLib.Web.Models.ChiTietMuonTra", b =>
                {
                    b.HasOne("SmartLib.Web.Models.CuonSach", "CuonSach")
                        .WithMany()
                        .HasForeignKey("MaCuonSach");

                    b.HasOne("SmartLib.Web.Models.MuonTra", "MuonTra")
                        .WithMany("ChiTietMuonTras")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach");

                    b.Navigation("CuonSach");

                    b.Navigation("MuonTra");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.CuonSach", b =>
                {
                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany("CuonSaches")
                        .HasForeignKey("MaSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.DanhGiaSach", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia");

                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach");

                    b.Navigation("DocGia");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.KeSach", b =>
                {
                    b.HasOne("SmartLib.Web.Models.NhaXuatBan", "NXBPhuTrach")
                        .WithMany()
                        .HasForeignKey("MaNXBPhuTrach")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartLib.Web.Models.TheLoai", "TheLoaiPhuTrach")
                        .WithMany()
                        .HasForeignKey("MaTheLoaiPhuTrach")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NXBPhuTrach");

                    b.Navigation("TheLoaiPhuTrach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.MuonTra", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany("MuonTras")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLib.Web.Models.NhanVien", "NhanVien")
                        .WithMany("MuonTras")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DocGia");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhanVien", b =>
                {
                    b.HasOne("SmartLib.Web.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhatKyHoatDong", b =>
                {
                    b.HasOne("SmartLib.Web.Models.NhanVien", "NhanVien")
                        .WithMany("NhatKyHoatDongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Reservation", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia");

                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach");

                    b.Navigation("DocGia");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Sach", b =>
                {
                    b.HasOne("SmartLib.Web.Models.KeSach", "KeSach")
                        .WithMany("Saches")
                        .HasForeignKey("MaKe");

                    b.HasOne("SmartLib.Web.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Saches")
                        .HasForeignKey("MaNXB");

                    b.HasOne("SmartLib.Web.Models.TheLoai", "TheLoai")
                        .WithMany("Saches")
                        .HasForeignKey("MaTheLoai");

                    b.Navigation("KeSach");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Sach_TacGia", b =>
                {
                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany("SachTacGias")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLib.Web.Models.TacGia", "TacGia")
                        .WithMany("SachTacGias")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TheThuVien", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany("TheThiViens")
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.ThongBao", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia");

                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocGia");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Wishlist", b =>
                {
                    b.HasOne("SmartLib.Web.Models.WishlistFolder", "Folder")
                        .WithMany("Wishlists")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia");

                    b.HasOne("SmartLib.Web.Models.Sach", "Sach")
                        .WithMany()
                        .HasForeignKey("MaSach");

                    b.Navigation("DocGia");

                    b.Navigation("Folder");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("SmartLib.Web.Models.WishlistFolder", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia");

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.WishlistPreference", b =>
                {
                    b.HasOne("SmartLib.Web.Models.DocGia", "DocGia")
                        .WithMany()
                        .HasForeignKey("MaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocGia");
                });

            modelBuilder.Entity("SmartLib.Web.Models.DocGia", b =>
                {
                    b.Navigation("MuonTras");

                    b.Navigation("TheThiViens");
                });

            modelBuilder.Entity("SmartLib.Web.Models.KeSach", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("SmartLib.Web.Models.MuonTra", b =>
                {
                    b.Navigation("ChiTietMuonTras");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("SmartLib.Web.Models.NhanVien", b =>
                {
                    b.Navigation("MuonTras");

                    b.Navigation("NhatKyHoatDongs");
                });

            modelBuilder.Entity("SmartLib.Web.Models.Sach", b =>
                {
                    b.Navigation("CuonSaches");

                    b.Navigation("SachTacGias");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TacGia", b =>
                {
                    b.Navigation("SachTacGias");
                });

            modelBuilder.Entity("SmartLib.Web.Models.TheLoai", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("SmartLib.Web.Models.WishlistFolder", b =>
                {
                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
