<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Helpers\**" />
	  <Content Remove="Helpers\**" />
	  <EmbeddedResource Remove="Helpers\**" />
	  <None Remove="Helpers\**" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Repositories\" />
		<Folder Include="wwwroot\assets\js\" />
	</ItemGroup>

	<ItemGroup>

		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />

		<PackageReference Include="ClosedXML" Version="0.105.0" />

		<PackageReference Include="MailKit" Version="4.17.0" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.9" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
		</PackageReference>

		<PackageReference Include="QuestPDF" Version="2026.5.0" />

		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />

		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://api.bitbucket.org/schemas/pipelines-configuration" /></VisualStudio></ProjectExtensions>

</Project>